// @ts-nocheck
/**
 * Skill metadata for pptx-template-editor repo scripts.
 * Used by /api/seed/route.ts for GitHub-based seeding.
 */

export interface SkillMeta {
  category: string;
  description: string;
  scriptPath: string;
  filename: string;
  name: string;
  language: string;
  params: string;
  inputFiles: string;
  outputFiles: string;
  tags: string;
}

export const PPTX_SKILLS: SkillMeta[] = [
  // ─── AI / Media Processing ──────────────────────────
  { name: 'Speech Recognition (ASR)', description: 'Automatic speech recognition using z-ai-web-dev-sdk. Transcribes audio files to text with support for multiple audio formats.', category: 'AI / Media', scriptPath: 'skills/ASR/scripts/asr.ts', filename: 'asr.ts', language: 'typescript', params: '[{"name":"audio_path","type":"file","description":"Audio file path","required":true}]', inputFiles: '[{"name":"audio_input","description":"Audio file to transcribe","required":true,"format":"mp3/wav/m4a"}]', outputFiles: '[{"name":"transcript","description":"Transcribed text","format":"txt"}]', tags: '["ai","asr","speech","transcription","audio"]' },
  { name: 'LLM Chat Completion', description: 'Large language model chat completion using z-ai-web-dev-sdk. Supports multi-turn conversations, system prompts, and context management.', category: 'AI / Media', scriptPath: 'skills/LLM/scripts/chat.ts', filename: 'llm_chat.ts', language: 'typescript', params: '[{"name":"message","type":"string","description":"User message","required":true},{"name":"system_prompt","type":"string","description":"System prompt","required":false}]', inputFiles: '[]', outputFiles: '[{"name":"response","description":"LLM response","format":"txt"}]', tags: '["ai","llm","chat","conversation","gpt"]' },
  { name: 'Text to Speech (TTS)', description: 'Text-to-speech synthesis using z-ai-web-dev-sdk. Converts text input into natural-sounding audio output.', category: 'AI / Media', scriptPath: 'skills/TTS/tts.ts', filename: 'tts.ts', language: 'typescript', params: '[{"name":"text","type":"string","description":"Text to synthesize","required":true}]', inputFiles: '[]', outputFiles: '[{"name":"audio_output","description":"Synthesized audio","format":"mp3"}]', tags: '["ai","tts","speech","synthesis","audio"]' },
  { name: 'Vision Language Model (VLM)', description: 'Vision-language model for image understanding using z-ai-web-dev-sdk. Analyzes images and provides detailed descriptions.', category: 'AI / Media', scriptPath: 'skills/VLM/scripts/vlm.ts', filename: 'vlm.ts', language: 'typescript', params: '[{"name":"image_url","type":"string","description":"Image URL or base64","required":true},{"name":"question","type":"string","description":"Question about the image","required":false}]', inputFiles: '[{"name":"image_input","description":"Image to analyze","required":true,"format":"jpg/png"}]', outputFiles: '[{"name":"analysis","description":"Image analysis result","format":"txt"}]', tags: '["ai","vlm","vision","image","multimodal"]' },
  { name: 'Image Editor', description: 'AI-powered image editing using z-ai-web-dev-sdk. Modify images with text instructions.', category: 'AI / Media', scriptPath: 'skills/image-edit/scripts/image-edit.ts', filename: 'image-edit.ts', language: 'typescript', params: '[{"name":"image","type":"file","description":"Source image","required":true},{"name":"instruction","type":"string","description":"Edit instruction","required":true}]', inputFiles: '[{"name":"source_image","description":"Image to edit","required":true,"format":"jpg/png"}]', outputFiles: '[{"name":"edited_image","description":"Edited image","format":"jpg/png"}]', tags: '["ai","image","edit","transformation"]' },
  { name: 'AI Image Generator', description: 'AI image generation using z-ai-web-dev-sdk. Create images from text descriptions with multiple sizes and styles.', category: 'AI / Media', scriptPath: 'skills/image-generation/scripts/image-generation.ts', filename: 'image-generation.ts', language: 'typescript', params: '[{"name":"prompt","type":"string","description":"Image description","required":true}]', inputFiles: '[]', outputFiles: '[{"name":"generated_image","description":"Generated image","format":"jpg/png"}]', tags: '["ai","image","generation","artwork","creative"]' },
  { name: 'Image Understanding', description: 'Image understanding and analysis using z-ai-web-dev-sdk. Provides detailed visual content descriptions and object detection.', category: 'AI / Media', scriptPath: 'skills/image-understand/scripts/image-understand.ts', filename: 'image-understand.ts', language: 'typescript', params: '[{"name":"image","type":"file","description":"Image to analyze","required":true}]', inputFiles: '[{"name":"image_input","description":"Image to understand","required":true,"format":"jpg/png"}]', outputFiles: '[{"name":"analysis","description":"Understanding result","format":"txt"}]', tags: '["ai","image","understanding","analysis","vision"]' },
  { name: 'Video Generator', description: 'AI video generation using z-ai-web-dev-sdk. Generate videos from text descriptions or images.', category: 'AI / Media', scriptPath: 'skills/video-generation/scripts/video.ts', filename: 'video-generation.ts', language: 'typescript', params: '[{"name":"prompt","type":"string","description":"Video description","required":true}]', inputFiles: '[]', outputFiles: '[{"name":"video_output","description":"Generated video","format":"mp4"}]', tags: '["ai","video","generation","creative"]' },
  { name: 'Video Understanding', description: 'Video content understanding using z-ai-web-dev-sdk. Analyzes video content and extracts information from frames.', category: 'AI / Media', scriptPath: 'skills/video-understand/scripts/video-understand.ts', filename: 'video-understand.ts', language: 'typescript', params: '[{"name":"video_path","type":"file","description":"Video file path","required":true}]', inputFiles: '[{"name":"video_input","description":"Video to analyze","required":true,"format":"mp4/avi/mov"}]', outputFiles: '[{"name":"analysis","description":"Video analysis result","format":"txt"}]', tags: '["ai","video","understanding","analysis"]' },
  // ─── Web / Search ──────────────────────────
  { name: 'Web Search', description: 'Web search using z-ai-web-dev-sdk. Search the web for real-time information with structured results.', category: 'Web / Search', scriptPath: 'skills/web-search/scripts/web_search.ts', filename: 'web_search.ts', language: 'typescript', params: '[{"name":"query","type":"string","description":"Search query","required":true}]', inputFiles: '[]', outputFiles: '[{"name":"results","description":"Search results","format":"json"}]', tags: '["web","search","information","retrieval"]' },
  { name: 'Web Page Reader', description: 'Web page content extraction using z-ai-web-dev-sdk. Scrapes web pages and extracts article content.', category: 'Web / Search', scriptPath: 'skills/web-reader/scripts/web-reader.ts', filename: 'web-reader.ts', language: 'typescript', params: '[{"name":"url","type":"string","description":"Web page URL","required":true}]', inputFiles: '[]', outputFiles: '[{"name":"content","description":"Extracted content","format":"html/txt"}]', tags: '["web","reader","scraper","extraction"]' },
  // ─── Academic / Research ──────────────────────────
  { name: 'AMiner Academic Search', description: 'Academic paper and scholar search using AMiner Open Platform. Search for papers, citations, scholars, and institutions.', category: 'Academic / Research', scriptPath: 'skills/aminer-academic-search/scripts/aminer.py', filename: 'aminer_search.py', language: 'python', params: '[{"name":"query","type":"string","description":"Search query","required":true}]', inputFiles: '[]', outputFiles: '[{"name":"results","description":"Search results","format":"json"}]', tags: '["academic","research","papers","citations","scholar"]' },
  { name: 'Paper Recommendation Engine', description: 'Personalized academic paper recommendations using AMiner. Get daily paper recommendations based on topics and authors.', category: 'Academic / Research', scriptPath: 'skills/aminer-daily-paper/scripts/recommend.py', filename: 'paper_recommend.py', language: 'python', params: '[{"name":"topic","type":"string","description":"Research topic","required":true}]', inputFiles: '[]', outputFiles: '[{"name":"papers","description":"Recommended papers","format":"json"}]', tags: '["academic","papers","recommendation","research"]' },
  // ─── Document Processing ──────────────────────────
  { name: 'PDF to Image Converter', description: 'Convert PDF pages to JPEG images using PyMuPDF (fitz). Supports configurable DPI, quality, and max file size.', category: 'Document Processing', scriptPath: 'scripts/pdf2img.py', filename: 'pdf2img.py', language: 'python', params: '[{"name":"pdf_path","type":"file","description":"Input PDF file path","required":true},{"name":"dpi","type":"number","description":"Render DPI","required":false,"default":"150"}]', inputFiles: '[{"name":"pdf_input","description":"PDF file to convert","required":true,"format":"pdf"}]', outputFiles: '[{"name":"image_output","description":"Converted JPEG images","format":"jpg"}]', tags: '["pdf","image","conversion","pymupdf"]' },
  { name: 'DOCX Document Generator', description: 'Generate and manipulate Word (.docx) documents programmatically. Supports formatting, tables, headers/footers, and TOC.', category: 'Document Processing', scriptPath: 'skills/docx/scripts/document.py', filename: 'docx_document.py', language: 'python', params: '[{"name":"template","type":"file","description":"DOCX template","required":false}]', inputFiles: '[{"name":"docx_template","description":"Word template","required":false,"format":"docx"}]', outputFiles: '[{"name":"docx_output","description":"Generated document","format":"docx"}]', tags: '["docx","word","document","template","office"]' },
  { name: 'DOCX TOC Placeholder Inserter', description: 'Add table of contents placeholders to Word documents. Inserts TOC field codes with customizable heading levels.', category: 'Document Processing', scriptPath: 'skills/docx/scripts/add_toc_placeholders.py', filename: 'add_toc_placeholders.py', language: 'python', params: '[{"name":"input","type":"file","description":"Input DOCX file","required":true}]', inputFiles: '[{"name":"docx_input","description":"Word document","required":true,"format":"docx"}]', outputFiles: '[{"name":"docx_output","description":"Document with TOC","format":"docx"}]', tags: '["docx","toc","word","document"]' },
  { name: 'PDF Design Engine', description: 'Advanced PDF design and typesetting engine. Supports complex layouts, typography, color systems, and cover design.', category: 'Document Processing', scriptPath: 'skills/pdf/scripts/design_engine.py', filename: 'pdf_design_engine.py', language: 'python', params: '[{"name":"config","type":"file","description":"Design configuration JSON","required":true}]', inputFiles: '[{"name":"config_json","description":"Design configuration","required":true,"format":"json"}]', outputFiles: '[{"name":"pdf_output","description":"Generated PDF","format":"pdf"}]', tags: '["pdf","design","typesetting","layout","publication"]' },
  { name: 'HTML to PDF Converter', description: 'Convert HTML content to PDF using Next.js-based rendering pipeline. Supports CSS styling and complex layouts.', category: 'Document Processing', scriptPath: 'skills/pdf/scripts/html2pdf-next.js', filename: 'html2pdf-next.js', language: 'javascript', params: '[{"name":"html_path","type":"file","description":"Input HTML file","required":true}]', inputFiles: '[{"name":"html_input","description":"HTML file","required":true,"format":"html"}]', outputFiles: '[{"name":"pdf_output","description":"Converted PDF","format":"pdf"}]', tags: '["pdf","html","conversion","rendering"]' },
  { name: 'HTML to Poster Converter', description: 'Convert HTML content to poster-format PDF documents with print-quality rendering.', category: 'Document Processing', scriptPath: 'skills/pdf/scripts/html2poster.js', filename: 'html2poster.js', language: 'javascript', params: '[{"name":"html_path","type":"file","description":"Input HTML file","required":true}]', inputFiles: '[{"name":"html_input","description":"HTML file","required":true,"format":"html"}]', outputFiles: '[{"name":"poster_output","description":"Poster PDF","format":"pdf"}]', tags: '["pdf","poster","html","conversion","print"]' },
  { name: 'PDF QA System', description: 'Question-answering system for PDF documents. Extracts text, indexes content, and answers natural language questions.', category: 'Document Processing', scriptPath: 'skills/pdf/scripts/pdf_qa.py', filename: 'pdf_qa.py', language: 'python', params: '[{"name":"pdf_path","type":"file","description":"Input PDF","required":true},{"name":"question","type":"string","description":"Question to answer","required":true}]', inputFiles: '[{"name":"pdf_input","description":"PDF document","required":true,"format":"pdf"}]', outputFiles: '[{"name":"answer","description":"Answer to question","format":"txt"}]', tags: '["pdf","qa","question","answer","document"]' },
  { name: 'PDF Cover Validator', description: 'Validate PDF cover pages against design specifications. Checks dimensions, color profiles, and layout compliance.', category: 'Document Processing', scriptPath: 'skills/pdf/scripts/cover_validate.js', filename: 'pdf_cover_validate.js', language: 'javascript', params: '[{"name":"pdf_path","type":"file","description":"PDF to validate","required":true}]', inputFiles: '[{"name":"pdf_input","description":"PDF cover","required":true,"format":"pdf"}]', outputFiles: '[{"name":"validation_report","description":"Validation results","format":"json"}]', tags: '["pdf","cover","validation","design","quality"]' },
  { name: 'Poster Layout Validator', description: 'Validate poster layout and design specifications. Checks spacing, font sizes, image resolution, and visual hierarchy.', category: 'Document Processing', scriptPath: 'skills/pdf/scripts/poster_validate.py', filename: 'poster_validate.py', language: 'python', params: '[{"name":"pdf_path","type":"file","description":"Poster PDF","required":true}]', inputFiles: '[{"name":"pdf_input","description":"Poster PDF","required":true,"format":"pdf"}]', outputFiles: '[{"name":"report","description":"Validation report","format":"json"}]', tags: '["pdf","poster","validation","layout"]' },
  { name: 'TOC Validator', description: 'Validate table of contents in PDF documents. Checks heading hierarchy and page number accuracy.', category: 'Document Processing', scriptPath: 'skills/pdf/scripts/toc_validate.py', filename: 'toc_validate.py', language: 'python', params: '[{"name":"pdf_path","type":"file","description":"PDF with TOC","required":true}]', inputFiles: '[{"name":"pdf_input","description":"PDF document","required":true,"format":"pdf"}]', outputFiles: '[{"name":"report","description":"TOC validation report","format":"json"}]', tags: '["pdf","toc","validation","document"]' },
  // ─── PPTX / Presentation ──────────────────────────
  { name: 'HTML to PPTX Converter', description: 'Convert HTML content to PowerPoint presentations. Supports slide layouts, text formatting, images, tables, and charts.', category: 'Presentation', scriptPath: 'skills/ppt/scripts/html2pptx.js', filename: 'html2pptx.js', language: 'javascript', params: '[{"name":"html_path","type":"file","description":"Input HTML file","required":true}]', inputFiles: '[{"name":"html_input","description":"HTML file","required":true,"format":"html"}]', outputFiles: '[{"name":"pptx_output","description":"Generated PPTX","format":"pptx"}]', tags: '["pptx","html","conversion","presentation","powerpoint"]' },
  { name: 'PPTX Slide Inventory', description: 'Inventory and catalog PowerPoint slide contents. Extracts slide structure, element counts, and layout information.', category: 'Presentation', scriptPath: 'skills/ppt/scripts/inventory.py', filename: 'ppt_inventory.py', language: 'python', params: '[{"name":"input","type":"file","description":"Input PPTX file","required":true}]', inputFiles: '[{"name":"pptx_input","description":"PowerPoint file","required":true,"format":"pptx"}]', outputFiles: '[{"name":"inventory_report","description":"Slide inventory","format":"json"}]', tags: '["pptx","inventory","catalog","presentation"]' },
  { name: 'PPTX Slide Rearranger', description: 'Rearrange slides in PowerPoint presentations. Supports reordering, duplicating, removing, and grouping.', category: 'Presentation', scriptPath: 'skills/ppt/scripts/rearrange.py', filename: 'ppt_rearrange.py', language: 'python', params: '[{"name":"input","type":"file","description":"Input PPTX","required":true},{"name":"order","type":"string","description":"New slide order","required":true}]', inputFiles: '[{"name":"pptx_input","description":"PowerPoint file","required":true,"format":"pptx"}]', outputFiles: '[{"name":"pptx_output","description":"Rearranged PPTX","format":"pptx"}]', tags: '["pptx","rearrange","slides","presentation"]' },
  { name: 'PPTX Template Replacer', description: 'Replace {{placeholder}} tokens in PowerPoint templates with data. Supports text and table replacement.', category: 'Presentation', scriptPath: 'skills/ppt/scripts/replace.py', filename: 'ppt_replace.py', language: 'python', params: '[{"name":"input","type":"file","description":"Input PPTX template","required":true},{"name":"data","type":"file","description":"JSON replacement data","required":true}]', inputFiles: '[{"name":"pptx_template","description":"PPTX template","required":true,"format":"pptx"},{"name":"replacements_json","description":"Replacement data","required":true,"format":"json"}]', outputFiles: '[{"name":"pptx_output","description":"Generated PPTX","format":"pptx"}]', tags: '["pptx","template","replace","placeholder"]' },
  { name: 'PPTX Thumbnail Generator', description: 'Generate thumbnail images from PowerPoint slides with configurable resolution.', category: 'Presentation', scriptPath: 'skills/ppt/scripts/thumbnail.py', filename: 'ppt_thumbnail.py', language: 'python', params: '[{"name":"input","type":"file","description":"Input PPTX","required":true},{"name":"width","type":"number","description":"Thumbnail width","required":false,"default":"320"}]', inputFiles: '[{"name":"pptx_input","description":"PowerPoint file","required":true,"format":"pptx"}]', outputFiles: '[{"name":"thumbnails","description":"Slide thumbnails","format":"jpg/png"}]', tags: '["pptx","thumbnail","preview","presentation"]' },
  { name: 'PPTX to PDF Converter', description: 'Convert PowerPoint presentations to PDF format. Preserves layout, formatting, and embedded media.', category: 'Presentation', scriptPath: 'skills/ppt/scripts/pdf.py', filename: 'ppt_to_pdf.py', language: 'python', params: '[{"name":"input","type":"file","description":"Input PPTX","required":true}]', inputFiles: '[{"name":"pptx_input","description":"PowerPoint file","required":true,"format":"pptx"}]', outputFiles: '[{"name":"pdf_output","description":"Converted PDF","format":"pdf"}]', tags: '["pptx","pdf","conversion","presentation"]' },
  // ─── OOXML Processing ──────────────────────────
  { name: 'OOXML Pack', description: 'Pack loose XML files into OOXML packages (.pptx, .docx). Handles content types and relationships.', category: 'OOXML Processing', scriptPath: 'skills/ppt/ooxml/scripts/pack.py', filename: 'ooxml_pack.py', language: 'python', params: '[{"name":"source_dir","type":"string","description":"XML source directory","required":true},{"name":"output","type":"string","description":"Output file","required":true}]', inputFiles: '[{"name":"xml_files","description":"XML source","required":true,"format":"xml"}]', outputFiles: '[{"name":"ooxml_output","description":"OOXML package","format":"pptx/docx"}]', tags: '["ooxml","pack","xml","office"]' },
  { name: 'OOXML Unpack', description: 'Unpack OOXML packages into component XML files for inspection and editing.', category: 'OOXML Processing', scriptPath: 'skills/ppt/ooxml/scripts/unpack.py', filename: 'ooxml_unpack.py', language: 'python', params: '[{"name":"input","type":"file","description":"OOXML file","required":true}]', inputFiles: '[{"name":"ooxml_input","description":"OOXML package","required":true,"format":"pptx/docx"}]', outputFiles: '[{"name":"xml_files","description":"Extracted XML","format":"xml"}]', tags: '["ooxml","unpack","xml","office"]' },
  { name: 'OOXML Validator', description: 'Validate OOXML packages against ISO/IEC 29500 and ECMA-376 schemas.', category: 'OOXML Processing', scriptPath: 'skills/ppt/ooxml/scripts/validate.py', filename: 'ooxml_validate.py', language: 'python', params: '[{"name":"input","type":"file","description":"OOXML file","required":true}]', inputFiles: '[{"name":"ooxml_input","description":"OOXML package","required":true,"format":"pptx/docx"}]', outputFiles: '[{"name":"validation_report","description":"Validation results","format":"json"}]', tags: '["ooxml","validate","schema","iso"]' },
  // ─── Career / Job ──────────────────────────
  { name: 'JD Parser', description: 'Parse and extract structured data from job descriptions. Identifies skills, experience, and education requirements.', category: 'Career / Job', scriptPath: 'skills/jd-resume-tailor/scripts/parse_jd.py', filename: 'parse_jd.py', language: 'python', params: '[{"name":"jd_text","type":"file","description":"Job description text","required":true}]', inputFiles: '[{"name":"jd_input","description":"Job description","required":true,"format":"txt"}]', outputFiles: '[{"name":"parsed_jd","description":"Structured JD data","format":"json"}]', tags: '["jd","parser","job","career","nlp"]' },
  { name: 'JD Gap Analyzer', description: 'Analyze gaps between a resume and job description. Provides alignment scores and improvement recommendations.', category: 'Career / Job', scriptPath: 'skills/jd-resume-tailor/scripts/jd_gap.py', filename: 'jd_gap.py', language: 'python', params: '[{"name":"resume","type":"file","description":"Resume file","required":true},{"name":"jd","type":"file","description":"Job description","required":true}]', inputFiles: '[{"name":"resume_input","description":"Resume","required":true,"format":"txt/pdf"},{"name":"jd_input","description":"Job description","required":true,"format":"txt"}]', outputFiles: '[{"name":"gap_analysis","description":"Gap analysis report","format":"json"}]', tags: '["jd","gap","resume","career","analysis"]' },
  { name: 'Job Intent Tracker', description: 'Initialize job search tracking database with application status, deadlines, and follow-up reminders.', category: 'Career / Job', scriptPath: 'skills/job-intent-tracker/scripts/init_tracker.py', filename: 'init_job_tracker.py', language: 'python', params: '[{"name":"profile","type":"file","description":"Job seeker profile JSON","required":true}]', inputFiles: '[{"name":"profile_json","description":"Job seeker profile","required":true,"format":"json"}]', outputFiles: '[{"name":"tracker_db","description":"Job tracker database","format":"json"}]', tags: '["job","tracker","career","search"]' },
  { name: 'Profile Matcher', description: 'Match job seeker profiles against job requirements with compatibility scores.', category: 'Career / Job', scriptPath: 'skills/job-intent-tracker/scripts/profile_match.py', filename: 'profile_match.py', language: 'python', params: '[{"name":"profile","type":"file","description":"Job seeker profile","required":true},{"name":"jd","type":"file","description":"Job description","required":true}]', inputFiles: '[{"name":"profile_json","description":"Job seeker profile","required":true,"format":"json"}]', outputFiles: '[{"name":"match_report","description":"Match analysis","format":"json"}]', tags: '["profile","match","career","job"]' },
  { name: 'ATS Resume Checker', description: 'Check resume compatibility with Applicant Tracking Systems. Provides ATS optimization score and suggestions.', category: 'Career / Job', scriptPath: 'skills/resume-builder/scripts/ats_check.py', filename: 'ats_check.py', language: 'python', params: '[{"name":"resume","type":"file","description":"Resume file","required":true}]', inputFiles: '[{"name":"resume_input","description":"Resume to check","required":true,"format":"pdf/docx/txt"}]', outputFiles: '[{"name":"ats_report","description":"ATS compatibility report","format":"json"}]', tags: '["ats","resume","career","optimization"]' },
  { name: 'STAR Story Builder', description: 'Build structured STAR (Situation, Task, Action, Result) stories for behavioral interviews.', category: 'Career / Job', scriptPath: 'skills/interview-prep/scripts/star_story_builder.py', filename: 'star_story_builder.py', language: 'python', params: '[{"name":"experience","type":"string","description":"Experience description","required":true}]', inputFiles: '[]', outputFiles: '[{"name":"star_story","description":"Formatted STAR story","format":"txt"}]', tags: '["star","interview","career","behavioral"]' },
  // ─── Content / Creative ──────────────────────────
  { name: 'Blog Example Manager', description: 'Manage and organize blog post examples. Supports creating, categorizing, and searching reference content.', category: 'Content / Creative', scriptPath: 'skills/blog-writer/manage_examples.py', filename: 'blog_examples.py', language: 'python', params: '[{"name":"action","type":"string","description":"Action (list/add/search)","required":true}]', inputFiles: '[]', outputFiles: '[{"name":"results","description":"Action results","format":"json"}]', tags: '["blog","content","examples","management"]' },
  { name: 'Market Research Visuals', description: 'Generate visual charts for market research reports. Creates bar charts, pie charts, and comparison tables.', category: 'Content / Creative', scriptPath: 'skills/market-research-reports/scripts/generate_market_visuals.py', filename: 'market_visuals.py', language: 'python', params: '[{"name":"data","type":"file","description":"Market data CSV/JSON","required":true}]', inputFiles: '[{"name":"data_input","description":"Market data","required":true,"format":"csv/json"}]', outputFiles: '[{"name":"chart_output","description":"Generated chart","format":"png/svg"}]', tags: '["market","research","visuals","charts"]' },
  { name: 'Podcast Episode Generator', description: 'Generate podcast episodes from text content. Converts articles into conversational scripts with multiple speakers.', category: 'Content / Creative', scriptPath: 'skills/podcast-generate/generate.ts', filename: 'podcast_generate.ts', language: 'typescript', params: '[{"name":"content","type":"file","description":"Source content file","required":true}]', inputFiles: '[{"name":"content_input","description":"Source content","required":true,"format":"txt/md"}]', outputFiles: '[{"name":"podcast_script","description":"Podcast script","format":"json/txt"}]', tags: '["podcast","content","audio","generation"]' },
  // ─── Quiz / Education ──────────────────────────
  { name: 'Quiz HTML Builder', description: 'Build interactive quiz HTML pages from question banks. Supports multiple question types and scoring.', category: 'Quiz / Education', scriptPath: 'skills/quiz-html/scripts/build_quiz_html.py', filename: 'build_quiz_html.py', language: 'python', params: '[{"name":"questions","type":"file","description":"Questions JSON","required":true}]', inputFiles: '[{"name":"questions_json","description":"Question bank","required":true,"format":"json"}]', outputFiles: '[{"name":"quiz_html","description":"Interactive quiz page","format":"html"}]', tags: '["quiz","html","education","interactive"]' },
  { name: 'Quiz Generator from Material', description: 'Generate quiz questions from study material using NLP. Creates multiple-choice, fill-in-blank, and short answer questions.', category: 'Quiz / Education', scriptPath: 'skills/quiz-mastery/scripts/generate_from_material.py', filename: 'quiz_from_material.py', language: 'python', params: '[{"name":"material","type":"file","description":"Study material file","required":true}]', inputFiles: '[{"name":"material_input","description":"Study material","required":true,"format":"txt/pdf"}]', outputFiles: '[{"name":"quiz_json","description":"Generated questions","format":"json"}]', tags: '["quiz","education","generation","nlp"]' },
  { name: 'Quiz Runner', description: 'Run interactive quizzes with scoring, timing, and progress tracking. Supports adaptive difficulty.', category: 'Quiz / Education', scriptPath: 'skills/quiz-mastery/scripts/run_quiz.py', filename: 'run_quiz.py', language: 'python', params: '[{"name":"quiz_file","type":"file","description":"Quiz JSON file","required":true}]', inputFiles: '[{"name":"quiz_input","description":"Quiz data","required":true,"format":"json"}]', outputFiles: '[{"name":"results","description":"Quiz results","format":"json"}]', tags: '["quiz","education","runner","interactive"]' },
  // ─── Data / Spreadsheet ──────────────────────────
  { name: 'XLSX Handler', description: 'Comprehensive Excel processor. Creates, reads, and modifies .xlsx files with charts, formulas, and formatting.', category: 'Data / Spreadsheet', scriptPath: 'skills/xlsx/xlsx.py', filename: 'xlsx_handler.py', language: 'python', params: '[{"name":"input","type":"file","description":"Input XLSX","required":false},{"name":"action","type":"string","description":"Action (create/read/edit)","required":true}]', inputFiles: '[{"name":"xlsx_input","description":"Excel file","required":false,"format":"xlsx/csv"}]', outputFiles: '[{"name":"xlsx_output","description":"Processed spreadsheet","format":"xlsx"}]', tags: '["xlsx","excel","spreadsheet","data","charts"]' },
  // ─── Finance ──────────────────────────
  { name: 'Stock Analyzer', description: 'Comprehensive stock analysis with technical and fundamental analysis, dividend tracking, and market monitoring.', category: 'Finance', scriptPath: 'skills/stock-analysis-skill/src/analyzer.ts', filename: 'stock_analyzer.ts', language: 'typescript', params: '[{"name":"symbol","type":"string","description":"Stock symbol","required":true}]', inputFiles: '[]', outputFiles: '[{"name":"analysis_report","description":"Stock analysis","format":"json"}]', tags: '["finance","stock","analysis","market"]' },
  { name: 'Stock Data Fetcher', description: 'Fetch real-time and historical stock market data with configurable time ranges and metrics.', category: 'Finance', scriptPath: 'skills/stock-analysis-skill/src/dataFetcher.ts', filename: 'stock_data_fetcher.ts', language: 'typescript', params: '[{"name":"symbol","type":"string","description":"Stock symbol","required":true}]', inputFiles: '[]', outputFiles: '[{"name":"market_data","description":"Market data","format":"json"}]', tags: '["finance","stock","data","market"]' },
  { name: 'Dividend Tracker', description: 'Track and analyze stock dividend payments with yield calculations and income projections.', category: 'Finance', scriptPath: 'skills/stock-analysis-skill/src/dividend.ts', filename: 'dividend_tracker.ts', language: 'typescript', params: '[{"name":"symbol","type":"string","description":"Stock symbol","required":true}]', inputFiles: '[]', outputFiles: '[{"name":"dividend_data","description":"Dividend analysis","format":"json"}]', tags: '["finance","dividend","stock","income"]' },
  // ─── Web / Shader ──────────────────────────
  { name: 'WebGL Shader Extractor', description: 'Extract WebGL/Canvas/Shader visual effects from web pages. Deobfuscates and ports shader code to standalone JS.', category: 'Web / Shader', scriptPath: 'skills/web-shader-extractor/scripts/fetch-rendered-dom.mjs', filename: 'shader_extract_dom.mjs', language: 'javascript', params: '[{"name":"url","type":"string","description":"Web page URL","required":true}]', inputFiles: '[]', outputFiles: '[{"name":"shader_code","description":"Extracted shader code","format":"js/glsl"}]', tags: '["shader","webgl","extractor","visual"]' },
  { name: 'Shader Bundle Scanner', description: 'Scan JavaScript bundles for embedded shader code. Identifies vertex/fragment shaders and uniform definitions.', category: 'Web / Shader', scriptPath: 'skills/web-shader-extractor/scripts/scan-bundle.sh', filename: 'shader_scan_bundle.sh', language: 'bash', params: '[{"name":"bundle_path","type":"file","description":"JS bundle file","required":true}]', inputFiles: '[{"name":"js_bundle","description":"JavaScript bundle","required":true,"format":"js"}]', outputFiles: '[{"name":"shader_report","description":"Scan results","format":"json"}]', tags: '["shader","scanner","webgl","bundle"]' },
  // ─── Lifestyle / Fun ──────────────────────────
  { name: 'Lunar Calendar / Fortune', description: 'Chinese lunar calendar calculations and fortune analysis. Converts between solar and lunar dates.', category: 'Lifestyle / Fun', scriptPath: 'skills/get-fortune-analysis/lunar_python.py', filename: 'lunar_python.py', language: 'python', params: '[{"name":"date","type":"string","description":"Date (YYYY-MM-DD)","required":true}]', inputFiles: '[]', outputFiles: '[{"name":"fortune","description":"Fortune analysis","format":"json"}]', tags: '["lunar","fortune","chinese","zodiac"]' },
  // ─── Creative / Writing ──────────────────────────
  { name: 'Storyboard Consistency Checker', description: 'Check story consistency across scenes. Validates character behaviors, timeline coherence, and plot logic.', category: 'Creative / Writing', scriptPath: 'skills/storyboard-manager/scripts/consistency_checker.py', filename: 'story_consistency.py', language: 'python', params: '[{"name":"story","type":"file","description":"Story file","required":true}]', inputFiles: '[{"name":"story_input","description":"Story content","required":true,"format":"txt/md"}]', outputFiles: '[{"name":"consistency_report","description":"Check results","format":"json"}]', tags: '["story","consistency","writing","creative"]' },
  { name: 'Storyboard Timeline Tracker', description: 'Track and visualize story timelines. Maps events chronologically and detects timeline conflicts.', category: 'Creative / Writing', scriptPath: 'skills/storyboard-manager/scripts/timeline_tracker.py', filename: 'story_timeline.py', language: 'python', params: '[{"name":"story","type":"file","description":"Story file","required":true}]', inputFiles: '[{"name":"story_input","description":"Story content","required":true,"format":"txt/md"}]', outputFiles: '[{"name":"timeline","description":"Timeline visualization","format":"json"}]', tags: '["story","timeline","writing","creative"]' },
  // ─── Developer Tools ──────────────────────────
  { name: 'Skill Description Improver', description: 'Improve and optimize skill descriptions using NLP techniques for better trigger accuracy and clarity.', category: 'Developer Tools', scriptPath: 'skills/skill-creator/scripts/improve_description.py', filename: 'improve_skill_desc.py', language: 'python', params: '[{"name":"description","type":"string","description":"Skill description to improve","required":true}]', inputFiles: '[]', outputFiles: '[{"name":"improved","description":"Improved description","format":"txt"}]', tags: '["skill","description","optimization","nlp"]' },
  { name: 'Skill Eval Runner', description: 'Run evaluation benchmarks for AI skills. Measures accuracy and performance with detailed reports.', category: 'Developer Tools', scriptPath: 'skills/skill-creator/scripts/run_eval.py', filename: 'skill_run_eval.py', language: 'python', params: '[{"name":"skill_path","type":"string","description":"Skill directory path","required":true}]', inputFiles: '[{"name":"test_input","description":"Test data","required":false,"format":"json"}]', outputFiles: '[{"name":"eval_report","description":"Evaluation report","format":"json"}]', tags: '["skill","eval","benchmark","testing"]' },
  // ─── Design / UI ──────────────────────────
  { name: 'UI/UX Design System Generator', description: 'Generate design system configurations for web projects. Creates color palettes, typography scales, and spacing systems.', category: 'Design / UI', scriptPath: 'skills/ui-ux-pro-max/scripts/design_system.py', filename: 'design_system_gen.py', language: 'python', params: '[{"name":"style","type":"string","description":"Design style","required":true},{"name":"brand_color","type":"string","description":"Primary brand color","required":false}]', inputFiles: '[]', outputFiles: '[{"name":"design_system","description":"Design system config","format":"json"}]', tags: '["design","ui","ux","system","colors"]' },
  // ─── Research ──────────────────────────
  { name: 'Research HTML Generator', description: 'Generate HTML research reports with proper formatting, citations, and visual hierarchy.', category: 'Content / Creative', scriptPath: 'skills/qingyan-research/generate_html.py', filename: 'research_html_gen.py', language: 'python', params: '[{"name":"data","type":"file","description":"Research data JSON","required":true}]', inputFiles: '[{"name":"data_input","description":"Research data","required":true,"format":"json"}]', outputFiles: '[{"name":"html_output","description":"Research report HTML","format":"html"}]', tags: '["research","html","report","generator"]' },
  { name: 'Skill Finder (CN)', description: 'Search and discover AI skills in Chinese. Supports natural language queries and keyword matching.', category: 'Developer Tools', scriptPath: 'skills/skill-finder-cn/scripts/search.sh', filename: 'skill_finder_cn.sh', language: 'bash', params: '[{"name":"query","type":"string","description":"Search query in Chinese","required":true}]', inputFiles: '[]', outputFiles: '[{"name":"results","description":"Search results","format":"json"}]', tags: '["skill","search","chinese","finder"]' },
];
